//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUCPROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aution()
        {
            this.Bids = new HashSet<Bids>();
        }
    
        public int idAution { get; set; }
        public System.DateTime FinishDate { get; set; }
        public float InitialPrice { get; set; }
        public float SoldPrice { get; set; }
        public int AutionOwner { get; set; }
        public int ProductOnSell { get; set; }
        public Nullable<int> AuctionBuyer { get; set; }
        public byte AuctionState { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bids> Bids { get; set; }
    }
}
