//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUCPROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Aution = new HashSet<Aution>();
        }
    
        public int idProduct { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Specs { get; set; }
        public int Category { get; set; }
        public byte[] Product_img { get; set; }
        public byte[] Product_img_1 { get; set; }
        public byte[] Product_img_2 { get; set; }
        public byte[] Product_img_3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aution> Aution { get; set; }
        public virtual Category Category1 { get; set; }
    }
}
